### ISSUE TITLE
미완성 이슈

### ISSUE THREAD

**Issue by caboooom** [nhnacademy-aiot1-5/api-service#2]
오늘 할 일 끝난 줄 알고 퇴근했는데
저희가 놓친 부분이 너무 많았습니다...

1. DB 연결 안 되어 있음
2. 회원 단일조회는 인증서버에서 인증에 쓰기 위한 api이므로, 응답으로 password도 포함시켜서 보내주어야함
3. 회원 생성시 password를 그대로 저장하면 안 되고, BcryptEncoder로 인코딩 해야 함
4. Dooray messenger 읽지 않음 (연락 안 됨 이슈)
5. Push만 하고, pull request 던지지 않았음
6. 다른 서버들과 api 협의 안 되었음

**Comment by haedanui** [comment]
https://jjangadadcodingdiary.tistory.com/entry/%EC%8A%A4%ED%94%84%EB%A7%81%EC%97%90%EC%84%9C-BCryptPasswordEncoder%EB%A5%BC-%ED%99%9C%EC%9A%A9%ED%95%9C-%EC%95%88%EC%A0%84%ED%95%9C-%EB%B9%84%EB%B0%80%EB%B2%88%ED%98%B8-%EC%95%94%ED%98%B8%ED%99%94
BcryptEncoder를 사용하는데 참조한 링크입니다.
